# Generated by Django 2.1.5 on 2019-01-06 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techou', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='purchase_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='pharmacy_name',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='message',
            name='medicine_name',
        ),
        migrations.AddField(
            model_name='message',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
