# Generated by Django 2.1.5 on 2019-01-07 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techou', '0004_message_pharmacy_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='purchase_date',
            field=models.CharField(max_length=255),
        ),
    ]
